### ISSUE TITLE
Please update

### ISSUE THREAD

**Issue by rlee1990** [alvarezGarciaMarcos/better_forms#3]
Because every version of better_forms depends on provider ^4.3.3 and giphy_get 2.0.0 depends on provider ^5.0.0, better_forms is incompatible with giphy_get 2.0.0.

And because no versions of giphy_get match >2.0.0 <3.0.0, better_forms is incompatible with giphy_get ^2.0.0.

So, because social depends on both giphy_get ^2.0.0 and better_forms ^0.0.2-beta1, version solving failed.
pub get failed (1; So, because social depends on both giphy_get ^2.0.0 and better_forms ^0.0.2-beta1, version solving failed.)
exit code 1

**Comment by alvarezGarciaMarcos** [comment]
Hi, first of all, thank your for taking your time to report this bug.
I have published a new version _0.0.2-beta2_ that fixes the problem with the _provider_ dependencies, the _provider_ version has been upgraded to _5.0.0_, so there should't be any kind of conflicts with other packages that use the same version.

Thank you.

**Comment by rlee1990** [comment]
@alvarezGarciaMarcos Thank you
